### ISSUE TITLE
aws SYSTEM_DOMAIN value should be elastic ip

### ISSUE THREAD

**Issue by jbayer** [cf-platform-eng/lattice-terraform#1]
i was able to stop / start instances and have an aws lattice environment start working again. however the SYSTEM_DOMAIN value was from the original public IP address instead of the new public IP address from the coordinator VM. ideally this is IP is set to an elastic IP that will either be assigned to the coordinator VM (when there is only 1 in the simple case).

i'm not sure how it lattice is already configurable enough to support a custom system domain which might go to a route53 domain and then to an ELB before being load balanced to several routers inside of coordinator VMs or otherwise.

https://github.com/cf-platform-eng/lattice-terraform/blob/689ede747b7c6d87705e4c145e8244393cb89c5d/aws/resources.tf#L79

**Comment by jbayer** [comment]
in the restarted coordinator instance i was able to change /var/lattice/setup so that the SYSTEM_DOMAIN had the new public ip and then issue a `sudo initctl receptor stop` and `sudo initctl receptor start`.

in the process i got an error trying to sudo.

```
ubuntu@ip-10-0-1-166:/var/lattice/config$ sudo su
sudo: unable to resolve host ip-10-0-1-166
root@ip-10-0-1-166:/var/lattice/config# sudo initctl stop receptor
sudo: unable to resolve host ip-10-0-1-166
receptor stop/waiting
```
i didn't realize i had indeed become root despite the resolve warning.

in any case, i was able to edit /etc/hosts to have an entry like this:
```
10.0.1.166 ip-10-0-1-166
```
presumably there is something in the root profile setup that highlights this hostname issue.

**Comment by frodenas** [comment]
The sudo problem has been fixed in commit https://github.com/cf-platform-eng/lattice-terraform/commit/2019d500f570739bdb1b7613d34a161d0142b4e0.

**Comment by frodenas** [comment]
There's a chicken-egg problem with terraform when trying to use an elastic IP and pass it to bootstrap the instance. 

If you want to create an elastic IP and attach it to an existing instance, the dependency graph mandates that the instance must exist before creating the eip, so we cannot use the eip address at instance bootstrap time (because we don't known yet the ip address). 

If we create first an eip and pass it later to the instance bootstrap process, we cannot assign the eip to the instance, because the instance resource doesn't accept eip as a param, and the eip resource must be called only 1 time during the apply process (we cannot create it first and assign it to an instance later).

One option might be creating and attaching the eip to the instance, and not pass this eip to the bootstrap process. The bootstrap process can gather this info from the user-data (this is what the original bootstrap process does: https://github.com/pivotal-cf-experimental/lattice/blob/master/common/setup/bootstrap#L16). But this can fail miserably if the bootstrap process is executed before the eip is assigned to the instance.

Another option might be not bootstrapping the system domain, and add a command to `ltc` to add domains on-the-fly (ala `cf create-domain`).

**Comment by jbayer** [comment]
is it true that only the coordinator VMs need to be configured with the updated SYSTEM_DOMAIN? if so maybe there is a post-install process that would act on the coordinator VMs
* update `SYSTEM_DOMAIN` in `/var/lattice/setup`
* stop/start the `receptor` service

/cc @onsi

**Comment by frodenas** [comment]
Terraform doesn't allow post-install processes. All actions against a resource must be performed on a single iteration, so there's no way we can update the instance with the system domain. Same happens with elastic IPs.

**Comment by jbayer** [comment]
right, i meant to say a post-terraform apply process done by the user either manually or via scripting

**Comment by frodenas** [comment]
Closing, as this project has been integrated into the [Lattice](https://github.com/pivotal-cf-experimental/lattice) project.
